### ISSUE TITLE
Feature Request: allow to use plugins (like imagemin-pngquant)

### ISSUE THREAD

**Issue by danielberndt** [tcoopman/image-webpack-loader#10]
I really would like to use the [imagemin-pngquant](https://github.com/imagemin/imagemin-pngquant) plugin. 
I have been using it in gulp-imagemin like [this](https://github.com/sindresorhus/gulp-imagemin#usage)

Would be great to see this supported for webpack as well, since pngquant's results are quite significant!

**Comment by tcoopman** [comment]
Do you want to be able to use plugins, or just this plugin?

I can see to add this plugin if you want to.

**Comment by danielberndt** [comment]
I'm personally just interested in the pngquant plugin, since it's the only plugin I'm aware of. Anything else would be a nice-to-have though.

**Comment by tcoopman** [comment]
Added support in 1.5.0. Make sure to use the json notation (see the readme)

**Comment by danielberndt** [comment]
:+1: thanks!
