### ISSUE TITLE
Would you consider to add webp-loader? 

### ISSUE THREAD

**Issue by brandonxiang** [tcoopman/image-webpack-loader#102]
Would you consider to add webp-loader with [imagemin-webp](https://github.com/imagemin/imagemin-webp)? 

Or I write a PR for it?

**Comment by tcoopman** [comment]
If you can write a PR that would be awesome

**Comment by Zephir77167** [comment]
Would also love to see this! @brandonxiang are you willing to do the PR or should I work on it?

**Comment by brandonxiang** [comment]
@Zephir77167 you please

**Comment by brandonxiang** [comment]
@Zephir77167  referencing to https://github.com/kavu/webp-loader

**Comment by Zephir77167** [comment]
Ok I will do it, but I think it has more to do with https://github.com/imagemin/imagemin-webp
