### ISSUE TITLE
Version 3.4.0 breaks the build

### ISSUE THREAD

**Issue by dstarosta** [tcoopman/image-webpack-loader#107]
Hi.

I am getting the following errors for PNG files with the recently released v3.4.0. The issue happens on Windows 2016 Server.

      ERROR in ./img/error/error-404.png
Module build failed : error : CoCreateInstance(MAKE_REFGUID(CLSID_WICImagingFactory), NULL, CLSCTX_INPROC_SERVER, MAKE_REFGUID(IID_IWICImagingFactory), (LPVOID*)&factory) failed 80040154 [c:\jenkins\workspace\Ad Sales - Advertisement Units - DEV\scm.build.proj]
      Couldn't access Windows Imaging Component (are you running Windows XP SP3 or newer?). Most formats not available. Use -s for the available YUV input.
      Decoding of input data failed.
      Status: 3(BITSTREAM_ERROR)
      Error! Could not process file C:\Users\scmrel\AppData\Local\Temp\c8d137c3-953f-45dd-a9ef-0cf6fd39fdc4
      Error! Cannot read input picture file 'C:\Users\scmrel\AppData\Local\Temp\c8d137c3-953f-45dd-a9ef-0cf6fd39fdc4'

`          at Promise.all.then.arr (c:\jenkins\workspace\Ad Sales - Advertisement Units - DEV\node_modules\execa\index.js:231:11)
          at process._tickCallback (internal/process/next_tick.js:109:7)
       @ ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/less-loader/dist/cjs.js!./node_modules/@espn-ese-adsales/react-common/src/components/toastr/ese-toastr.less 6:4715-4744`

It seems to be related to the added webp support. My settings are as follows. Any help would be appreciated.

                    loader: 'image-webpack-loader',
                    options: {
                        bypassOnDebug: true,
                        mozjpeg: { progressive: true },
                        gifsicle: { interlaced: true },
                        optipng: { optimizationLevel: 7 },
                        svgo: {
                            plugins: [{ removeViewBox: false }, { removeEmptyAttrs: false }]
                        }
                    }

**Comment by tcoopman** [comment]
@Zephir77167 can you have a look?

**Comment by Zephir77167** [comment]
I will take a look shortly

**Comment by Zephir77167** [comment]
I just tested on a small project and two larges projects with hundreds of images, with both your config and mine, and didn't run into the issue.

Could you provide your OS, node version and package.json please?

Also, did you update other dependencies along with `image-webpack-loader`?

**Comment by dstarosta** [comment]
The OS is Windows Server 2016. It does not happen on Windows 7. Node version is 6.10.3.

I was able to "fix" the issue by disabling webp using `webp: { enabled: false }`. Downgrading `image-webpack-loader` also works.

It looks like something on the server does not support the format. The strange thing is I do not have any images in that format.

**Comment by luigiplr** [comment]
It appears to be encoding png's as web's.

Opening up compressed png's presents `RIFF@WEBPVP8X` vs what it should be `PNG`

**Comment by Zephir77167** [comment]
Ok totally my bad, just figured out imagemin-webp takes JPG|PNG as input and outputs WEBPs. Wondering how I missed this when reading the docs.

It should therefore be disabled by default, and enabled if you want to generate a WEBP version of your images. I will make a PR soon and update the README

**Comment by Zephir77167** [comment]
https://github.com/tcoopman/image-webpack-loader/pull/108 will fix this, sorry about the inconvenience folks

**Comment by Chance722** [comment]
I am getting the same error today by require image path in my javascript file.

**Comment by Zephir77167** [comment]
Hi, temporary workaround : `webp: { enabled: false }`.

#108 should fix this when it is merged/a new version is released. Sorry about that!
