### ISSUE TITLE
Unexpected character '�' (1:0) when importing image

### ISSUE THREAD

**Issue by adambarghouthi** [tcoopman/image-webpack-loader#116]
Hi guys - I'm fairly new to webpack and I can't seem to get image loading to work. I set up image-webpack-loader as instructed. See below: 

```
import webpack from 'webpack';
import merge from 'webpack-merge';
import path from 'path';
import fs from 'fs';
import isDev from 'isdev';
import ExtractTextPlugin from 'extract-text-webpack-plugin';
import { Dir } from './src/utils';

const TARGET = process.env.npm_lifecycle_event;

let Config = {
  entry: [
    'babel-polyfill',
    'react-hot-loader/patch',
    path.join(Dir.src, 'client'),
    path.join(Dir.src, 'client/sass/main.sass'),
  ],
  output: {
    path: Dir.build,
    filename: 'bundle.js',
  },
  resolve: {
    modules: [Dir.src, 'node_modules'],
    extensions: ['*', '.js', '.jsx', '.json'],
  },
  node: {
    fs: "empty"
  },
  module: {
    rules: [
      {
        test: /\.js?$/,
        enforce: 'pre',
        loader: 'eslint-loader',
        exclude: /node_modules/,
        include: Dir.src,
      },
      {
        test: /\.js?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.(sass|scss)$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader'],
        }),
      },
      {
        test: /\.(gif|png|jpe?g|svg)$/i,
        loaders: [
          'file-loader?hash=sha512&digest=hex&name=[hash].[ext]',
          'image-webpack-loader',
        ],
      },
    ],
  },
  plugins: [
    new ExtractTextPlugin({
      filename: '[name].bundle.css',
      allChunks: true,
    }),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
      },
    }),
  ],
};

if (TARGET === 'build:prod' && !isDev) {
  Config = merge(Config, {
    bail: true,
    devtool: 'source-map',
    output: { publicPath: '/build/' },
    plugins: [
      new webpack.optimize.DedupePlugin(),
      new webpack.optimize.UglifyJsPlugin({
        comments: false,
        dropDebugger: true,
        dropConsole: true,
        compressor: {
          warnings: false,
        },
      }),
    ],
  });
}

if (TARGET === 'server:dev' && isDev) {
  Config = merge(Config, {
    devtool: 'eval',
    entry: ['webpack-hot-middleware/client'],
    plugins: [
      new webpack.HotModuleReplacementPlugin(),
      new webpack.NoEmitOnErrorsPlugin(),
    ],
  });
}

const WebpackConfig = Config;
export default WebpackConfig;
```
I have images in this folder as you can see:
![screen shot 2017-09-05 at 2 11 03 am](https://user-images.githubusercontent.com/8386869/30035701-83d21404-91df-11e7-88ce-51b3ce3aa803.png)

and when I add `import logo from '~/src/images/logo.png'` I get this error whilst compiling:
```
/Users/adambargh/Github/Yuma2.0/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
/Users/adambargh/Github/Yuma2.0/src/images/visa.png: Unexpected character '�' (1:0)
> 1 | �PNG
```

Not sure what the problem is, any help is appreciated. Thank you!

**Comment by xiaomingming** [comment]
same to  you!

**Comment by Zephir77167** [comment]
Which version are you using? If < 3.4.2, please try upgrading and tell us if this fixes it.

**Comment by adambarghouthi** [comment]
Hi @Zephir77167 - even when I updated it's still the same thing. Please help I need to get this feature up asap

**Comment by Zephir77167** [comment]
Unfortunately I don't think it comes from `image-webpack-plugin` as I never encountered this before. Could you reproduce the issue on a minimal repository so I could try and help you?

**Comment by iShawnWang** [comment]
Disable Hot Reloading solve my problem ~

**Comment by tsheaff** [comment]
I have this same problem, and I don't have hot reloading on at all and I'm just using a plain `file` loader.

```
  const imageLoader = {
    test: /\.(jpg|jpeg|gif|png|svg)$/,
    loaders: ['file'],
    include: [path.resolve(__dirname, 'assets/source/images')],
  };
```

**Comment by edwardmhunton** [comment]
I have the same issue - but if i start server without and put the images back in then it works...only when starting afresh does it fail. I see a reference to babylon (babel) here in your code...do you have the latest presents?

Have you always had this error? Has this png webpacked before?

**Comment by ErEllison** [comment]
just remove the `i` from end of regex for finding images:
/\.(gif|png|jpe?g|svg)$/i,


that i in the last , it will work...

**Comment by caprica-Six** [comment]
Not sure if this'll help, but [Next-images](https://github.com/twopluszero/next-images) helped me. Thank you

**Comment by ruojianll** [comment]
> just remove the `i` from end of regex for finding images: `/\.(gif|png|jpe?g|svg)$/i,` that i in the last , it will work... make it like this `/\.(gif|png|jpe?g|svg)$/,`

Works! Then I put the 'i' back, the issue resolved.
