### ISSUE TITLE
Lossless (PNG) source to lossy (JPEG/lossy WEBP) output?

### ISSUE THREAD

**Issue by tremby** [tcoopman/image-webpack-loader#118]
Is there a way with this package to specify that for particular images I want a lossily compressed output even though the input was losslessly compressed?

In other words:

- most/all of my input images are PNGs
- I want some of these to end up minified PNGs (and maybe lossless WEBP versions too)
- I want others of these to end up JPEGs (and maybe lossy WEBP versions too)

I'm OK with having a naming scheme for them, for example images which should end up lossy (photographic things generally) could have their source images called `*.lossy.png` and ones which should stay lossless could have their source images called `*.lossless.png`, or some similar scheme. Or I'm OK with specifying it some way at import time on a case by case basis.

**Comment by Zephir77167** [comment]
Hi, I think you can achieve this by defining two loaders:

```js
const loaders = [
{
    test: /.*\.lossy\.(eot|woff|woff2|ttf|svg|png|jpe?g|gif)$/i,
    use: [
      {
        loader: 'url-loader',
        options: {
          name: 'images/[name].[hash].[ext]',
        },
      },
      {
        loader: 'image-webpack-loader',
        options: {
          pngquant: {
            quality: '80-90',
            speed: 1,
          },
        },
      },
    ],
  },
{
    test: /.*\.lossless\.(eot|woff|woff2|ttf|svg|png|jpe?g|gif)$/i,
    use: [
      {
        loader: 'url-loader',
        options: {
          name: 'images/[name].[hash].[ext]',
        },
      },
    ],
  },
];
```

For example, and iff I understood well.

**Comment by tremby** [comment]
Thanks, but I don't see how this would convert PNG to JPEG in the lossy case. It looks like it'd just run it through pngquant and end up with another PNG (albeit, a dithered one).

**Comment by Zephir77167** [comment]
Oh I see, well you could always use the `webp` option, but as for the PNG to JPG... No idea

**Comment by tremby** [comment]
I guess perhaps it's out of scope for this loader.

The use case is that sometimes I'm given PNG source files of things which should really be JPEGs (photographic things), or I'm given a Photoshop file and need to export bits of composed layers. I like to ensure I'm getting the absolute minimum of second-generation compression artefacts, so I like in those cases to leave them as PNGs for as long as possible, and then they should only move to a lossy format during packaging.

I'm thinking now that this may belong elsewhere in the toolchain -- perhaps the loader which deals with resizing the images for srcsets.

I'm going to close this. Thanks for the pointer about using loaders with different regexes and configuration.
