### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by chenyiqi** [tcoopman/image-webpack-loader#119]
![d3e31e3e7fa82b9fa47845411d989c55](https://user-images.githubusercontent.com/3357208/30956526-3536d13e-a46a-11e7-8ebd-c63a2d5eddae.jpg)
Don't know how to solve

**Comment by mguijarr** [comment]
I have the same problem - no solution so far.

**Comment by chenyiqi** [comment]
npm i pngquant-bin  --save-dev

**Comment by chenyiqi** [comment]
The latest version needs to be installed

**Comment by mguijarr** [comment]
I installed it, but there is still no "vendor" directory. Weird.

**Comment by laysent** [comment]
try run `npm run postinstall` in that package folder, it should install the vendor correctly or throw error indicating where things go wrong.

**Comment by sevaru** [comment]
It possibly meant that postinstall script of pngquant-bin failed.
@chenyiqi Could you reinstall packages and show the output of you install?
