### ISSUE TITLE
Question: Is there a way to bundle images/svgs?

### ISSUE THREAD

**Issue by evandegr** [tcoopman/image-webpack-loader#12]
I would like to have svgs either bundled up all together in one or somehow bundle it along with my full production bundles. Is this possible?

**Comment by tcoopman** [comment]
Can you show me an example of this or a plugin that does this?

I'm not sure if this loader should do this though, but I'm willing to take a look at it.

**Comment by nesukun** [comment]
there are a few webs and tools that do so, like Shoebox, Visual Studio web essentials, imagepacker, there is probably a node package somewhere that does it.

**Comment by tcoopman** [comment]
You mean something like this: https://github.com/jkphl/gulp-svg-sprite?

How do you want to reference your images then?
I suppose you no do:
```
var globe = require('globe.svg');
var tree = require('tree.svg);
```

And you want those requires to be rewritten to point to the place in the sprite. Or do you mean something else?

**Comment by nesukun** [comment]
I really don't think this fits in this loader's scope. It's a nice idea for a loader, but I'd keep those two concerns separated.

**Comment by tcoopman** [comment]
I would rather not have this in the loader too. But bundling the svgs without being able to use them directly is not very useful I guess.

Either way, I would say that bundling of images and changes the requires is something for a different loader and out of scope for this one, so I'm going to close this item.
