### ISSUE TITLE
Example: Use with PostCSS/Blade PHP

### ISSUE THREAD

**Issue by strarsis** [tcoopman/image-webpack-loader#127]
An example would be nice which shows how to use this webpack loader together with PostCSS, 
like loading the same background image with different resolutions 
(https://github.com/SuperOl3g/postcss-image-set-polyfill) - or using it in PHP/Blade template file.

**Comment by anikethsaha** [comment]
Usage will be the same as the current as loaders process files independently. Its the work of webpack which groups together.

@tcoopman good to close 👍
