### ISSUE TITLE
Ubuntu 16.04 with image-webpack-loader 4.0.0 "Error: write EPIPE"

### ISSUE THREAD

**Issue by paullth** [tcoopman/image-webpack-loader#142]
Hi,

I keep getting this error when using v4.0.0:

    Module build failed: Error: write EPIPE
    at _errnoException (util.js:1031:13)
    at WriteWrap.afterWrite [as oncomplete] (net.js:873:14)

Ive created a simple repo which reliably recreates the problem for me https://github.com/paullth/image-webpack-loader_Error-write-epipe

    npm run build

results in  
    
    
        
    loader option has been deprecated - replace with "use"
    Hash: 5d1005e8f43b27754b31
    Version: webpack 2.7.0
    Time: 648ms
        Asset      Size  Chunks             Chunk Names
    bundle.js    4.2 kB       0  [emitted]  main
    style.css  35 bytes       0  [emitted]  main
       [0] ./src/image_viewer.js 449 bytes {0} [built]
       [1] ./src/sum.js 153 bytes {0} [built]
       [2] ./src/index.js 272 bytes {0} [built]
       [3] ./src/image_viewer.css 41 bytes {0} [built]
       [4] ./assets/big.jpeg 162 bytes {0} [built] [failed] [1 error]
       [5] ./assets/small.jpg 162 bytes {0} [built] [failed] [1 error]
       [6] ./~/css-loader/lib/css-base.js 2.28 kB [built]
    
    ERROR in ./assets/small.jpg
    Module build failed: Error: write EPIPE
        at _errnoException (util.js:1031:13)
        at WriteWrap.afterWrite [as oncomplete] (net.js:873:14)
     @ ./src/image_viewer.js 7:13-43
     @ ./src/index.js
    
    ERROR in ./assets/big.jpeg
    Module build failed: Error: write EPIPE
        at _errnoException (util.js:1031:13)
        at WriteWrap.afterWrite [as oncomplete] (net.js:873:14)
     @ ./src/image_viewer.js 3:11-40
     @ ./src/index.js
    Child extract-text-webpack-plugin:
           [0] ./~/css-loader/lib/css-base.js 2.28 kB {0} [built]
           [1] ./~/css-loader!./src/image_viewer.css 197 bytes {0} [built]
    npm ERR! code ELIFECYCLE
    npm ERR! errno 2
    npm ERR! js_modules@1.0.0 build: `webpack`
    npm ERR! Exit status 2
    npm ERR! 
    npm ERR! Failed at the js_modules@1.0.0 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:

**Comment by cschweda** [comment]
Just tried uploading this to Netlify, and I received the same exact error.

Had to remove the loader altogether in order to get a successful build.

**Comment by paullth** [comment]
I have found that changing to v3.6.0 allows it to build successfully

**Comment by cschweda** [comment]
Thanks -- I'll try that.

**Comment by piuccio** [comment]
Same thing here, Travis builds on 16.04

**Comment by cschweda** [comment]
The downgrade to 3.6 worked fine. Everything builds a-ok on Netlify and on Ubuntu 16.04.

**Comment by piuccio** [comment]
sure, downgrade works fine but it's not the way forward

**Comment by sman591** [comment]
Also seeing this error on Circle CI builds ever since 4.0.0, sound like a 4.0 bug.

**Comment by maayoko** [comment]
I'm getting this error only with jpe?g extensions. Png, svg, gif works fine on v4.1.0.
When downgrading to 3.6 everything works as expected.
I'm using ubuntu 16.04. Also have noticed the same issue with img-loader v2.0.1 (probably the same logic is used)

**Comment by sontek** [comment]
Just ran into this while upgrading, it was affecting only jpg.  Going to just the downgrade now.

**Comment by bymathias** [comment]
Same thing [here](https://github.com/bymathias/nexss) as well, build failed with 4.1.0 and jpg.

**Comment by zjensen17** [comment]
I'm running into the same issue, and it's blocking my team's upgrade to Webpack 4. Downgrading image loader back to 3.6 causes other problems with Webpack 4. Are there any fixes for this issue in the works?

**Comment by therealtbs** [comment]
This is apparently an issue with `imagemin-mozjpeg`. According to this comment https://github.com/imagemin/imagemin-mozjpeg/issues/28#issuecomment-377131250 you need to install `libpng16-dev` (`sudo apt-get install libpng16-dev`).

This fixed it for me on Ubuntu 16.04.1 LTS

**Comment by flexdinesh** [comment]
For anyone who's trying to get this to work in **Travis** build, 

`sudo apt-get install libpng16-dev` won't work as travis containers have a whitelist of packages - [ubuntu-trusty whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty)

`libpng16-dev` is not in the whitelist yet and I have created a new whitelist request for `libpng16-dev` - [libpng16-dev whitelist request](https://github.com/travis-ci/travis-ci/issues/9515). So until it is whitelisted we won't be able to get it work work in trusty containers.

As an alternative, I switched to osx environment temporarily to get this to work. Add this line to you `travis.yml` file

`os: osx`

And everything will work like a charm! 🎉

**Comment by Jorundur** [comment]
For a Debian environment see: https://github.com/tcoopman/image-webpack-loader/issues/136#issuecomment-365863976

I had this issue with CircleCI 2.0, running a Debian docker container, using webpack 3.11. Installing `nasm` did the job for me.

**Comment by JamesNimlos** [comment]
For those looking for a solution to a `node:8` Docker base, adding `RUN apt-get update && apt-get install nasm` worked for me.

**Comment by enapupe** [comment]
https://github.com/tcoopman/image-webpack-loader/issues/142#issuecomment-389324023
> For those looking for a solution to a node:8 Docker base, adding RUN apt-get update && apt-get install nasm worked for me like mentioned above.

Just don't forget to add it BEFORE installing npm dependencies, the nsm dep has to be available there.

**Comment by kaankucukx** [comment]
Same here! downgrading to 3.6 fixed it with webpack 3..

**Comment by gruckion** [comment]
# Docker
I got a warning that 'libpng16-dev' has been replaced with 'libpng-dev' I switched to this.

`RUN apt-get update && apt-get upgrade -y
RUN apt-get install -yq --no-install-recommends \
    libpng-dev \
    && apt-get clean`

My webpack 4 module: { rules: [] } is..

`                {
                    test: /\.(gif|png|jpe?g|svg)$/i,
                    use: [
                        'file-loader',
                        {
                            loader: 'image-webpack-loader',
                            options: {
                                debug: true,
                            },
                        },
                    ],
                },`

After making this change and using one of the below to render it I still get the same error in the docker build.

```
const Image = require("./images/some_image.png");
import Image from "./images/image.png";
```

> ERROR in ./features/semantic/images/avatar/large/matthew.png
  Module build failed (from ./node_modules/image-webpack-loader/index.js):
  Error
      at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
      at onErrorNT (internal/child_process.js:362:16)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)
   @ ./features/semantic/Sample.tsx 23:22-66
   @ ./features/app/components/App.tsx
   @ ./shared/index.tsx
   @ multi ./shared/index.tsx

**Comment by gbiryukov** [comment]
updating `image-webpack-loader` to version `4.5.0` solved this issue

**Comment by enapupe** [comment]
As this https://github.com/tcoopman/image-webpack-loader/issues/142#issuecomment-380751197 comment metioned, this seemed to be an issue with imagemin-mozpeg not this repo itself. This seems to be fixed on the dependency and I suppose this issue could be closed. 
I can also confirm updating fixed the issue.

**Comment by tribet84** [comment]
It still happens in `4.6.0`, downgrade to `4.5.0` and same :(
