### ISSUE TITLE
Can image-webpack-loader work with url-loader?

### ISSUE THREAD

**Issue by Congeek** [tcoopman/image-webpack-loader#146]
i'm worry about it will trigger confilct

**Comment by glemiere** [comment]
I'm using url-loader and get no compression. I guess it's not currently possible.

**Comment by JosueDevMark** [comment]
I'm using url-loader@1.0.1, webpack@4.1.1 with image-webpack-loader@4.2.0 and is working fine

**Comment by Congeek** [comment]
@JosueDevMark can you show me your config, i use url-loader and image-webpack-loader but get no ccompression

**Comment by Congeek** [comment]
@glemiere me too

**Comment by McGiogen** [comment]
I think this is the right (and simple) way:
```
{
  loader: 'url-loader',
  options: {
    limit: 8192,
    // and file-loader options here
  }
}, {
  loader: 'image-webpack-loader',
  options: {
    ...
  }
}
```
I have not tried yet but check resolved issues. [Example](https://github.com/tcoopman/image-webpack-loader/issues/118)

**Comment by glemiere** [comment]
It works.
In my case it was coming from a bad configuration or url-loader.

@Congeek you can check my configuration on my [project](https://github.com/glemiere/nextjs-starter). Hope it will help ;-)

**Comment by monsieurnebo** [comment]
I confirm that a rule based on tje @McGiogen 's example is working fine.

**Comment by anikethsaha** [comment]
Yes you can do it. Just make sure `url-loader` is before this loader as webpack loads loaders in reverse order. So you need to first process your image using this loader and then inject it into your file as a string using `url-loader`

@tcoopman I guess this issue is good to close 👍
