### ISSUE TITLE
image-webpack-loader requires that OS have libpng package installed?

### ISSUE THREAD

**Issue by leonardovillela** [tcoopman/image-webpack-loader#147]
Hello guys, good afternoon.

I use image-webpack-loader in my project. When install image-webpack-loader i get an error `Error: pngquant failed to build, make sure that libpng-dev is installed`. if it's really mandatory, would not it be the case to add this in the docs? and not only for a specific operating system, such as mac.

OS: Ubuntu 17.10.

**Comment by moyus** [comment]
same issue :(

**Comment by ceerqingting** [comment]
me to, how to solve this problem

**Comment by yyynnn** [comment]
yeah, same here on `win7`. - 
` × MaxRedirectsError: pngquant failed to build, make sure that libpng-dev is installed`.
would be cool to not include any dependency outside of npm

**Comment by EthanOrange** [comment]
same issuze
win10 x64
nodejs: v8.11.3
npm: v5.6.0
yarn: 1.7.0

**Comment by i-void** [comment]
Up

**Comment by tcoopman** [comment]
This is an issue with `imagemin-pngquant`. See https://github.com/imagemin/imagemin-pngquant/issues/46
