### ISSUE TITLE
Files not processed when webpack ran through the webpack-dev-server

### ISSUE THREAD

**Issue by newtonianb** [tcoopman/image-webpack-loader#15]
I just setup webpack-dev-server with the hot module replacement. Everything seems to work fine except I don't get any of my images or svg processed with this plugin like they do when I don't use the webpack-dev-server. They seem to bundle find and I even see in my css using the browser that the path to the svg was replaced with /assets/3234325awoe34.svg, how can I debug this?

Any idea the changes I need to make ?
```
gulp.task("webpack:dev-server", function(callback) {
  new WebpackDevServer(webpack(config), {
    publicPath: config.output.publicPath,
    hot: true,
    historyApiFallback: true,
    proxy: {
      "*": "http://myapp.app"
    }
  }).listen(8081, 'localhost', function (err, result) {
        if (err) {
          console.log(err);
        }
        callback()

        console.log('Listening at localhost');
      });
});
```

This is what use to work when I wasn't using the webpack-dev-server

```
                {
                    test: /\.(jpe?g|png|gif|svg)(?:\?.*|)$/i,
                    loaders: [
                        'file?hash=sha512&digest=hex&name=[hash].[ext]',
                        'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
                    ]
                },
```

**Comment by newtonianb** [comment]
Seems to be the issue in the file loader
https://github.com/webpack/file-loader/issues/3

**Comment by tcoopman** [comment]
I'm closing this as an issue with the file-loader. If you have any more questions, please let me know.
