### ISSUE TITLE
there is the error

### ISSUE THREAD

**Issue by colianghan** [tcoopman/image-webpack-loader#16]
![image](https://cloud.githubusercontent.com/assets/8284860/9218395/b981d4b4-4104-11e5-91e2-ff8bc336de30.png)
module:{
		preLoaders:[{
			test:/\.js$/,
			loader:'jshint-loader'
		},{
			test:/\.{jpg|jpeg|png|gif}$/i,
			loader:'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false}'
		}],
		loaders:[{
			test:/\.css$/,
			loader:'style-loader!css-loader'
		},{
			test:/\.html$/,
			loader:'html-loader'
		},{
			test:/(.*)[\/|\\]img[\/|\\]([^\/\\]*)\.{jpg|jpeg|png|gif}$/i,
			query:{
				regExp:'(img([\\\\|\/]?([^\\\/]*)?[\\\\|\/])*?([^\\\/]*)?\.(jpg|jpeg|png|gif)$)',
				name:'[1]'
			},
			loader:'file-loader'
		}]
	},

**Comment by tcoopman** [comment]
Hmmm, I'm wondering if this is a windows only problem.
Does your configuration work with other file types like _jpg_?

**Comment by oliviertassinari** [comment]
Same problem here on linux

**Comment by tcoopman** [comment]
@oliviertassinari can you reproduce it with only imagemin?

**Comment by oliviertassinari** [comment]
As far as I have look at it, it's link to an npm regression. See https://github.com/npm/npm/issues/8982.
I fixed this issue by using on older version of npm: `npm@2.12.1`.

**Comment by chenxsan** [comment]
I'm running against npm@2.14.3 on Windows 7, no more error.

**Comment by tcoopman** [comment]
I'm going to close this as a npm issue

**Comment by lcxfs1991** [comment]
I encounter same error when I upgrade from 1.8.0 to 2.0.0

**Comment by tcoopman** [comment]
@lcxfs1991 have you checked this: https://github.com/npm/npm/issues/8982

**Comment by lcxfs1991** [comment]
I use npm3

**Comment by akonyushevskiy** [comment]
I'm getting this error: 

`
ERROR in ./src/front/components/splash/splash-mobile.jpg
Module build failed: Error: spawn /home/admin/node/greatbytrain/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./~/css-loader!./~/resolve-url-loader!./~/sass-loader!./src/front/components/splash/styles.scss 6:95-125
`
Ubuntu 12.04
node 6.7.0
npm 3.10.8

**Comment by davidcalhoun** [comment]
Had a similar issue with `yarn`.  I think I had a botched install somehow.  Deleted the entire `node_modules` directory and re-installed (`yarn install`), that fixed it.

**Comment by oOBobbyOo** [comment]
![qq 20170801104503](https://user-images.githubusercontent.com/12425983/28807396-dffce4c8-76a7-11e7-9e74-686171af08e9.png)
How to solve?

**Comment by Gillardo** [comment]
Same error

![image](https://user-images.githubusercontent.com/7406381/30055731-404c587c-9228-11e7-9af2-9347d28bd5c8.png)

**Comment by hzlmn** [comment]
Same issue on Fedora with `npm@3.10.8` and `node 6.9.1`.

**Comment by hmhofman** [comment]
Had this issue today. 
`npm rebuild` seems to work...
https://github.com/imagemin/optipng-bin/issues/84#issuecomment-343403097

**Comment by lslucas** [comment]
Solved my problem updating npm
`sudo npm install -g npm`

**Comment by Pushplaybang** [comment]
> npm rebuild seems to work...

yup.  Did the trick.
