### ISSUE TITLE
gulp-util deprecation

### ISSUE THREAD

**Issue by baoduy** [tcoopman/image-webpack-loader#160]
The package gulp-util is depreciation. Should upgrade to an alternative one.

**Comment by avallete** [comment]
Actually, the error is related to: gifsicle.

imagemin-gifsicle use gifsicle@^3.0.0 (actually 3.0.4)
gifsicle@3.0.4 use bin-build@2.2.0 (witch has been updated to 3.0.0 to fix  gulp-util deprecation).

From the gifsicle repo, the fix seem to be already done, but the maintainer didn't publish the new version on npm yet.

(See: https://github.com/imagemin/gifsicle-bin/issues/92)

**Comment by pgd151** [comment]
The referenced 'fix'

	https://github.com/imagemin/gifsicle-bin/issues/92

is resolved as Closed.  The current gifsicle release is 4.0.1, as of Oct 30,

  https://github.com/imagemin/gifsicle-bin/releases

Here I've got
```
yarn list gifsicle imagemin-gifsicle image-webpack-loader imagemin-webp cwebp-bin bin-build download gulp-decompress
├─ bin-build@3.0.0
│  └─ download@6.2.5
├─ cwebp-bin@5.0.0
├─ download@7.1.0
├─ gifsicle@4.0.1
├─ gulp-decompress@2.0.2
├─ image-webpack-loader@4.5.0
│  ├─ bin-build@2.2.0
│  ├─ cwebp-bin@4.0.0
│  ├─ download@4.4.3
│  ├─ gulp-decompress@1.2.0
│  └─ imagemin-webp@4.1.0
├─ imagemin-gifsicle@6.0.1
└─ imagemin-webp@5.0.0
```

Yet I still get this deperecation warning on every yarn action,
```
warning image-webpack-loader > imagemin-webp > cwebp-bin > bin-build > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
```

Note that `gulp-decompress` had its gulp-util dep removed in v2.0.2,

> Remove deprecated `gulp-util` dependency
 https://github.com/kevva/gulp-decompress/commit/d3fdff17810f757056503b0f81a8c06f3fa9dc60 

This message is only coming from image-webpack-loader.

@tcoopman  What *specific* dependency is causing this constant warning?

**Comment by pgd151** [comment]
the subsequent v4.6.0 release does the trick.  warning/message gone. thanks! @tcoopman
