### ISSUE TITLE
Module not found: Error: Can't resolve 'image-webpack-loader'

### ISSUE THREAD

**Issue by sevaTechoPark** [tcoopman/image-webpack-loader#164]
after update ubuntu from 16 to 18
webpack try to find your `image-webpack-loader` in my app folder instead `node_modules`. If I remove this loader from my webpack.config.js all works fine. Thus, the matter is not in webpack. Help me pls!
So, this project build success by my friends from 18 ubuntu, but they don not update to 18 ubuntu, they originally installed 18 ubuntu

**Comment by tcoopman** [comment]
Can you check if you ran into this: https://github.com/webpack/webpack/issues/1083

**Comment by sevaTechoPark** [comment]
Yes I use `resolve` in my webpack 4 config

**Comment by sevaTechoPark** [comment]
In general, the problem was that webpack did not install this package in node_modules

**Comment by SambitKumarPatra** [comment]
> Yes I use `resolve` in my webpack 4 config

Can you please paste `resolve` part of your config.
I tried using it but I still get the error.
`**Module not found: Error: Can't resolve 'image-webpack-loader' in '/home/Client'**`

**Comment by ilyaDymshits** [comment]
you may update  'image-webpack-loader' version to 4.5.0. it should solve this issue.

**Comment by sevaTechoPark** [comment]
thank you all
 issue can be close
