### ISSUE TITLE
Please publish to npm registry

### ISSUE THREAD

**Issue by qanwi1970** [tcoopman/image-webpack-loader#168]
The code in the npm registry is 4 months old, but the last commit here was a month ago. Those of us in newer Linux distros could really use the fix from commit https://github.com/tcoopman/image-webpack-loader/commit/de849ec2f0eb86c72181b003009bec589b943a2b. The only way to get it is to specify this git repo in the version filed in package.json. Thank you.

**Comment by tcoopman** [comment]
Published `4.4.0`
