### ISSUE TITLE
npm install image-webpack-loader@4.6.0 fails at dependency install of gifsicle

### ISSUE THREAD

**Issue by ScottB-Work** [tcoopman/image-webpack-loader#175]
Hi, experiencing the issue on install of any image-webpack-loader module version. It fails at the installation of the gifsicle dependency and this is the case in previous versions also. Have tried to test if it is just gifsicle at fault and cannot independently install the imagemin-gifsicle module either. 

Is this something anyone else is encountering? Have added below the printout from the terminal post npm install attempt.

```
> cwebp-bin@5.0.0 postinstall /
Route to node modules folder /node_modules/cwebp-bin
> node lib/install.js
```

  ⚠ unable to get local issuer certificate
  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✔ cwebp built successfully

```
> gifsicle@4.0.1 postinstall /Route to node modules folder /node_modules/gifsicle
> node lib/install.js
```

  ⚠ unable to get local issuer certificate
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
`/bin/sh: autoreconf: command not found`

   ` at Promise.all.then.arr (/Route to node modules folder /node_modules/bin-build/node_modules/execa/index.js:231:11)`
    `at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by ScottB-Work** [comment]
These are the other dev dependencies if it helps:

`"devDependencies": {
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "babel-register": "^6.26.0",
    "chai": "^4.1.2",
    "chai-enzyme": "^0.8.0",
    "css-loader": "^0.28.7",
    "enzyme": "^2.9.1",
    "file-loader": "^2.0.0",
    "image-webpack-loader": "^4.6.0",
    "jsdom": "^11.12.0",
    "mocha": "^5.2.0",
    "node-sass": "^4.9.2",
    "react-dom": "^15.6.2",
    "react-router-dom": "^4.2.2",
    "react-test-renderer": "^16.0.0",
    "sass-loader": "^6.0.6",
    "sinon": "^4.0.0",
    "standard": "^10.0.3",
    "standard-loader": "^6.0.1",
    "style-loader": "^0.18.2",
    "stylelint": "^8.1.1",
    "stylelint-order": "^0.8.1",
    "stylelint-scss": "^2.1.0",
    "stylelint-webpack-plugin": "^0.10.5",
    "url-loader": "^1.1.2",
    "webpack": "^4.27.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"`

**Comment by ScottB-Work** [comment]
Was due to firewall proxy issue through employer now resolved. Though thanks for the speedy responses........

**Comment by kiranio** [comment]
@ScottB-Work ,
Hey mate, How exactly you solved this problem?  I ran into the same issue.

**Comment by ScottB-Work** [comment]
We have a corporate firewall for which a certificate is required to get traffic past, the resolution was to make this certificate available to npm and node via an export in the .bash_profile specifically the https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file

This resolved the issue for me anyway
