### ISSUE TITLE
Changelog or Release Notes

### ISSUE THREAD

**Issue by NathanKleekamp** [tcoopman/image-webpack-loader#176]
Thank you so much for your work on this loader! Can I humbly ask that you go back to maintaining the Changelog or release notes describing the changes between version. Comparing diff doesn't really communicate the differences between versions, and consumers of this awesome loader can't easily tell how those changes will affect their codebases. Thanks and you rock!!

**Comment by tcoopman** [comment]
Very good point. I'll try to maintain it again. You may always submit a PR to bring it up to date if you'd like to.
