### ISSUE TITLE
Request version bump of imagemin-optipng

### ISSUE THREAD

**Issue by shivam-kantival-mt** [tcoopman/image-webpack-loader#188]
Request version bump of `imagemin-optipng` to v7.

Version 7 of `imagemin-optipng` uses `optipng-bin@6` which has got binary of optipng committed into the repo.

Please refer to this commit for further details-
https://github.com/imagemin/optipng-bin/commit/6bb7f1c2edab67297c7d72fa0bd604ecc214b9f1

This is important as this reduces dependency on `sourceforge.net` servers. We faced a huge blackout recently as `http://downloads.sourceforge.net` was down for quite some time. We were not able to go ahead with any fresh builds for this time period.

**Comment by tcoopman** [comment]
should be fixed in `5.1.0`
