### ISSUE TITLE
Example on how to use

### ISSUE THREAD

**Issue by kevinsimper** [tcoopman/image-webpack-loader#19]
Right now if you try to require a svg you just get the filename, but I want the content of the svg after it has been through svgomg.

Is there an example on how to do that? I looked in the test folder, but found none.

**Comment by tcoopman** [comment]
The output is indeed a filename. If you want to get the contents of the you could try to use the https://github.com/webpack/url-loader with a big enough limit. This will return a data-url

**Comment by kevinsimper** [comment]
Ah, I did not know how the file-loader worked, and since I used the `webpack-dev-server`, I did not see the output, nor could I get it without specifying the, `output.publicPath` in my `webpack.config.js` file.

Soo many concepts to jungle, but thank you very much for this loader! :dancers: :smile:
