### ISSUE TITLE
image-webpack-loader not work actually

### ISSUE THREAD

**Issue by weekeight** [tcoopman/image-webpack-loader#20]
I config image-webpack-loader like this:

```
{
        test: /\.(jpe?g|png|gif|svg)$/i,
        loaders: [
          'file?hash=sha512&digest=hex&name=[hash].[ext]',
          'image-webpack?{optimizationLevel:7, imageminPngquant:{ floyd: 0.1, quality: 0 }}'
        ]
}
```

I have found whatever I change `optimizationLevel` to 0 or 7, the size of built image is not reduced...And I try almost options in the document, and nothing change, so what's the problem in this example? In another way, can you upload a example including config file and source image, so we can see whether the example works on my computer

**Comment by tcoopman** [comment]
Have you checked the example folder?

**Comment by weekeight** [comment]
@tcoopman Where can I find the example folder?I can't find it at  [https://github.com/tcoopman/image-webpack-loader](https://github.com/tcoopman/image-webpack-loader)

**Comment by tcoopman** [comment]
Sorry, I meant the test folder:https://github.com/tcoopman/image-webpack-loader/tree/master/test

Also some images are already compressed and will not change in size anymore.

**Comment by weekeight** [comment]
I try the test folder and it works! I found I used image-webpack-loader@1.6.1 and it works when I update to image-webpack-loader@1.6.2。In addition, it doesn't work using the config without ** pngquant** config like the following:

```
{
        test: /\.(jpe?g|png|gif|svg)$/i,
        loaders: [
          'file?hash=sha512&digest=hex&name=[hash].[ext]',
          'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false}'
        ]
}
```

But I am confused,building on [the official document](https://github.com/tcoopman/image-webpack-loader), would it reduct the size of png images by default? I mean without any **pngquant** config

**Comment by tcoopman** [comment]
The optimazationLevel is for pngs and is always used as you can see in the documentation too. If you think this is not clear, let me know how you think it would be better and I'll see if I can change it.

**Comment by weekeight** [comment]
As you said, *The optimazationLevel is for pngs*, but use the config like the following without the ** pngquant**, the size of png images won't be reduced... And you can try it in your test folder, you will see the result

```javascript
{
        test: /\.(jpe?g|png|gif|svg)$/i,
        loaders: [
          'file?hash=sha512&digest=hex&name=[hash].[ext]',
          'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false}'
        ]
}
```

**Comment by tcoopman** [comment]
I don't see any reason why it doesn't work. Have you tried directly with https://github.com/imagemin/imagemin-optipng?

Not a fix, but can you use pngquant at the moment? That does work.

**Comment by TheDutchCoder** [comment]
I have the same issue, nothing actually happens.
No errors either, so something's up.

Here's my config:
```
var path = require('path')
var config = require('../config')
var cssLoaders = require('./css-loaders')
var projectRoot = path.resolve(__dirname, '../')
var BrowserSyncPlugin = require('browser-sync-webpack-plugin');

module.exports = {
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    publicPath: config.build.assetsPublicPath,
    filename: '[name].js'
  },
  resolve: {
    extensions: ['', '.js', '.vue'],
    fallback: [path.join(__dirname, '../node_modules')],
    alias: {
      'src': path.resolve(__dirname, '../src'),
      'assets': path.resolve(__dirname, '../src/assets'),
      'components': path.resolve(__dirname, '../src/components')
    }
  },
  resolveLoader: {
    fallback: [path.join(__dirname, '../node_modules')]
  },
  module: {
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json'
      },
      {
        test: /\.html$/,
        loader: 'vue-html'
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        loaders: [
            'file?hash=sha512&digest=hex&name=[hash].[ext]',
            'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}'
        ]
      },
      {
        test: /\.(png|jpe?g|gif|svg|woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: path.join(config.build.assetsSubDirectory, '[name].[hash:7].[ext]')
        }
      }
    ]
  },
  vue: {
    loaders: cssLoaders()
  },
  eslint: {
    formatter: require('eslint-friendly-formatter')
  },
  plugins: [
    new BrowserSyncPlugin({
      host: 'localhost',
      port: 3000,
      proxy: 'http://localhost:8080'
    }, {
      reload: false
    })
  ]
}
```

**Comment by tcoopman** [comment]
can you test again with the latest version?

**Comment by tcoopman** [comment]
Please file a new issue if you still have this problem in the latest version
