### ISSUE TITLE
file-loader prereq

### ISSUE THREAD

**Issue by meanJim** [tcoopman/image-webpack-loader#21]
It's probably implied if you're knee deep in the *es6-nowait-es2015-react-webpack-babel-wait-wasnt-it-6to5-traceur-dontforgetpolymer-riotjs-mithril-endless-js-but-no-angular-tooling-celebration-party* that you need to have `file-loader` already.

But you would the the coolest guy ever if you add `npm install --save-dev file-loader` to the steps just in case someone didn't know.

Also jokes aside you are awesome, this loader works like a charm. :100: Thank you.

**Comment by tcoopman** [comment]
@meanJim, `file-loader` is already a dependency. See `package.json`. How did you run into this problem?

**Comment by tcoopman** [comment]
@meanJim `file-loader` is already a dependency. How did you run into this issue?

(sorry deleted old comment by mistake)
