### ISSUE TITLE
bump to imagemin 4

### ISSUE THREAD

**Issue by kilianc** [tcoopman/image-webpack-loader#22]
imagemin got broken because of a broken dep.

    something is very odd, it is being called twice

keeps showing up. ref https://github.com/imagemin/imagemin/issues/132

**Comment by djbobbydrake** [comment]
Am seeing the same issue on my end, with node 4.2.4

**Comment by djbobbydrake** [comment]
I downgraded to node 4.2.3 and that seems to have fixed the issue...

**Comment by tcoopman** [comment]
Done and released 1.6.3, sorry for the long wait.
