### ISSUE TITLE
Error: Cannot find module 'imagemin-pngquant'

### ISSUE THREAD

**Issue by SophinQ** [tcoopman/image-webpack-loader#246]
I installed 'image-webpack-loader', but I got this error message when I packaged my project.
[Error: Cannot find module 'imagemin-pngquant']

And after I installed 'imagemin-pngquant', it still didn't work. The error is ' Error: pngquant failed to build, make sure that libpng-dev is installed'

**Comment by SophinQ** [comment]
And after I installed 'imagemin-pngquant', it still didn't work.  The error is ' Error: pngquant failed to build, make sure that libpng-dev is installed'

**Comment by IvyWang-SH** [comment]
> I installed 'image-webpack-loader', but I got this error message when I packaged my project. [Error: Cannot find module 'imagemin-pngquant']
> 
> And after I installed 'imagemin-pngquant', it still didn't work. The error is ' Error: pngquant failed to build, make sure that libpng-dev is installed'

Hello,
I got the same issue. could you share your solutions? Thanks!
