### ISSUE TITLE
It doesn't work, the picture is not compressed

### ISSUE THREAD

**Issue by lixianbin1** [tcoopman/image-webpack-loader#252]
I follow the content of the documentation, but it does not work, I do not understand what went wrong.The file is packaged without error, but the picture is not compressed.
```
      {
        test: /\.(png|svg|jpg|jpeg|gif)$/,
        use: [{
            loader:'file-loader',
            options:{
                outputPath:"images/",
                publicPath:"./images",
            }
        },{
            loader: 'image-webpack-loader',
            options: {
              bypassOnDebug: true, // webpack@1.x
              disable: true, // webpack@2.x and newer
              mozjpeg: {
                progressive: true,
                quality: 65
              },
              optipng: {
                enabled: false,
              },
              pngquant: {
                quality: [0.65, 0.90],
                speed: 4
              },
              gifsicle: {
                interlaced: false,
              }
            },
       },]
      },
```

**Comment by lixianbin1** [comment]
There are also the following configuration
```
      {
        test: /\.(html)$/,
        use: {
          loader: 'html-loader',
          options: {
            attributes:{
              list:[
                {
                    tag:'img',
                    attribute:"src",
                    type:"src"
                },{
                    tag:'img',
                    attribute:"data-src",
                    type:"src"
                },
              ],
            },
            minimize:true
          }
        }
      }
```

**Comment by tcoopman** [comment]
you have `disable: true`, you should only set disable true for `development` not for a production build

**Comment by lixianbin1** [comment]
Is it set to "Disable: Error"? , But I first set'disable: false', and then packaged, a new problem appeared: "Cannot find the module'pngquant-bin"; libpng-dev does not exist in Windows, what should I do?

**Comment by lixianbin1** [comment]
Is it set to `disable: false`? , But I set`disable: false`, and then packaged, a new problem appeared: "Cannot find the module'pngquant-bin"; libpng-dev does not exist in Windows, what should I do?

**Comment by tcoopman** [comment]
I would take a look at the repository of `pngquant-bin` and find out why it doesn’t work on windows. Maybe try to reinstall the package.
I’m closing the issue because the original problem is solved.
