### ISSUE TITLE
Security issues Vulnerability

### ISSUE THREAD

**Issue by vladthelittleone** [tcoopman/image-webpack-loader#257]
`npm audit` returns high severity errors:

| High | Remote Memory Exposure |
|---|---|
| Package | bl |
| Dependency of | image-webpack-loader [dev]  |
| Path | image-webpack-loader > imagemin-gifsicle > gifsicle > bin-wrapper > download > decompress > decompress-tarbz2 >  decompress-tar > tar-stream > bl |                           
| More info | https://npmjs.com/advisories/1555 |

**Comment by tcoopman** [comment]
should be fixed in the next release
