### ISSUE TITLE
upgrade test to github actions

### ISSUE THREAD

**Issue by tcoopman** [tcoopman/image-webpack-loader#260]
if someone wants to create PR for this, that would be awesome.

**Comment by bassochette** [comment]
Hi, 
Do you mean setting up github actions to run tests on PR and merged commits in master?

**Comment by tcoopman** [comment]
Yes, indeed

**Comment by bassochette** [comment]
Cool, I'll send you a PR today.

**Comment by tcoopman** [comment]
Going to reopen for some of the remaining actions:

* add badge to the readme
* remove travis

**Comment by bassochette** [comment]
I can take care of that tomorrow.
BTW Do you want me to remove codeQL?

**Comment by tcoopman** [comment]
Thanks, let's keep codeQL for now. If it gives problems it's easy to remove again.
