### ISSUE TITLE
[Suggestion] add guide for containers(docker) and ci

### ISSUE THREAD

**Issue by vitoyucepi** [tcoopman/image-webpack-loader#262]
### Summary
After update I've researched how to build my project in container using gitlab-ci.
To build my project I have to build binary dependencies since image-webpack-loader@7.0.0 because gifsicle-bin have no prebuilt binaries.
I've checked:
- `node:12-buster`
- `node:12-buster-slim`
- `node:12-stretch`
- `node:12-stretch-slim`
- `node:12-alpine`
- `node:12-alpine3.9`

### My prepare script benchmark results:
1. `node:12-buster-slim`
  `node:12-stretch-slim`
  exec time: `3 minutes`
  Prepare script:
    ```sh
    apt-get update
    apt-get install -y --no-install-recommends autoconf automake g++ libpng-dev make
    ```
1. `node:12-buster`
  `node:12-stretch`
  exec time: `3 minutes 30 seconds`
  Prepare script: **NO**
1. `node:12-alpine`
  `node:12-alpine3.9`
  exec time: `4 minutes 20 seconds`
  Prepare script:
    ```sh
    apk add --no-cache autoconf automake file g++ libtool make nasm libpng-dev
    ```

### Why `alpine` is slow
There's no prebuilt binary packages for `musl`.

### Why `buster`(`stretch`) is slower than `buster-slim`(`stretch-slim`)
Full debian version is about 6x larger than slim version.

### My request
Add prepare scripts to readme or create wiki page for that.

### Additional info
imagemin/imagemin-gifsicle#32
imagemin/imagemin-gifsicle#40
imagemin/gifsicle-bin#79
imagemin/gifsicle-bin#113
imagemin/mozjpeg-bin#47
imagemin/optipng-bin#110

**Comment by tcoopman** [comment]
Can you create a PR for this?

**Comment by vitoyucepi** [comment]
@tcoopman should I create PR for `README.md`, another `.md` file or wiki page?

**Comment by tcoopman** [comment]
We don't have a wiki so far, so add it to the readme, we can refactor later if it would be too long

**Comment by tcoopman** [comment]
clised via: #266
