### ISSUE TITLE
How to disable WebP ? Seems a bug from v7.0.0

### ISSUE THREAD

**Issue by VincentClair** [tcoopman/image-webpack-loader#263]
I've got the following error when building package on serverless :
```
ERROR in ./app/assets/images/favicon.png
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: spawn /builds/webapp/node_modules/cwebp-bin/vendor/cwebp ENOENT
```
It seems that, what any option i set or not set to webp config, webp is activated:

Maybe it comes from options init at
https://github.com/tcoopman/image-webpack-loader/blob/83d8ea081e52e84cc4525dd4d5d0f12f8ccf3d65/index.js#L42

Then when initializing plugins, the condition is true, at
https://github.com/tcoopman/image-webpack-loader/blob/83d8ea081e52e84cc4525dd4d5d0f12f8ccf3d65/index.js#L82 :

Any idea to resolve it ?

**Comment by VincentClair** [comment]
Seems related to https://github.com/tcoopman/image-webpack-loader/commit/909bcf62e671ad8a8c2f75777d8e266bd37c0376

**Comment by tcoopman** [comment]
Have you tried setting config.webp to false?

**Comment by VincentClair** [comment]
Yes, and with line 42, it initiliaze wbep option to `{}`

**Comment by tcoopman** [comment]
Ah yes, I see. That's an issue indeed

**Comment by tcoopman** [comment]
removing `webp` from the config or setting `webp.enabled = false` should work again.
