### ISSUE TITLE
No file extensions on Debian.

### ISSUE THREAD

**Issue by ArnoBuschmann** [tcoopman/image-webpack-loader#27]
Hello, seems I have a strange problem with webpack and the webpack-image-loader, maybe anyone can help?

The thing is, that when using both locally on Ubuntu, everything works as expected and images were written *including* file extensions such as .svg, jpg. and so on. But when using the same project on Debian, files were written without extensions and the bundle fails.

The config looks like this:

```
{
  test: /\.(jpe?g|png|gif)$/i,
  loaders: [
    'file?hash=sha512&digest=hex&name=[hash].[ext]',
    'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}'
  ]
}
```

**Comment by tcoopman** [comment]
What is the exact error? Do you have the same issue with only the file
loader?

**Comment by ArnoBuschmann** [comment]
Thanks for your quick reply which is a life saver already because it runs at least now, because, actually the problem is not there, when using the file loader only. The error message is:

```
[1] [kotatsu] (v0.10.0)
[1] [kotatsu] Compiling...
[1] [kotatsu] Done!
[1] [kotatsu] Starting your script...
[0] [kotatsu] (v0.10.0)
[0] [kotatsu] Compiling...
[1] [kotatsu] HMR connected.
[0] events.js:154
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: write EPIPE
[0]     at exports._errnoException (util.js:890:11)
[0]     at WriteWrap.afterWrite (net.js:767:14)
[0] 
[0] npm
[0]  
[0] ERR!
[0]  Linux 3.2.0-4-amd64
[0] npm
```

**Comment by tcoopman** [comment]
Do you have the same versions of node and npm on Ubuntu and Debian?

**Comment by ArnoBuschmann** [comment]
I have node 5.0.0. on Ubuntu and 5.4.1 on Debian. So I changed to 5.0.0 on Debian and tried again, no luck, unfortunately.

**Comment by tcoopman** [comment]
Have you been able to fix this?

**Comment by lcxfs1991** [comment]
same issue on windows.

**Comment by tcoopman** [comment]
Can you try again with the latest version?

**Comment by tcoopman** [comment]
Please file a new issue if you still have this problem with the latest version.
