### ISSUE TITLE
Build on Windows fails

### ISSUE THREAD

**Issue by Olgagr** [tcoopman/image-webpack-loader#28]
I have a problem with using this loader on Windows machine. I use Jenkins with Windows for CI and during build I get this error:

```
Module not found: Error: Cannot resolve module 'file' in c:\jenkins\workspace\Magazine.Live.My.FeatureBranch\client\app\common\top_bar
resolve module file in c:\jenkins\workspace\Magazine.Live.My.FeatureBranch\client\app\common\top_bar
  looking for modules in c:\jenkins\workspace\Magazine.Live.My.FeatureBranch\node_modules
    module variation file-webpack-loader
      c:\jenkins\workspace\Magazine.Live.My.FeatureBranch\node_modules\file-webpack-loader doesn't exist (module as directory)
      resolve 'file' file-webpack-loader in c:\jenkins\workspace\Magazine.Live.My.FeatureBranch\node_modules
        resolve file
          c:\jenkins\workspace\Magazine.Live.My.FeatureBranch\node_modules\file-webpack-loader doesn't exist
```

Locally, I build on Mac and build is working.

I have image-webpack-loader added to in my package.json.

My webpack.config looks like this:

```
{ test: /\.(jpe?g|png|gif|svg)$/i, loaders: [
     'file?hash=sha512&digest=hex&name=[hash].[ext]',
     'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
   ] 
}
```

I import svg file in the file:

```
import logo from './../../../asset/img/logo.svg';
```

I guess problem can be in path to the image. During build the path to the file becomes ./asset/img/logo.svg.

**Comment by tcoopman** [comment]
Do you have the same problem with only the file loader?

**Comment by Olgagr** [comment]
@tcoopman Yes, I have this problem only with file loader.

**Comment by tcoopman** [comment]
Then I guess the problem has nothing to do with the image loader. My best
guess would be to look at the issues in the file loader and see if you can
solve your problem like that. Afterwards add the image loader again

**Comment by Olgagr** [comment]
Ok, the same story with just file loader. I'll look for solution in file loader project. Thanks.
