### ISSUE TITLE
How to use image-webpack-loader with url-loader

### ISSUE THREAD

**Issue by aseem2625** [tcoopman/image-webpack-loader#36]
I've 2 questions:

1) After optimizing where does it put the images? I tried dummy 1MB image and after running my webpack, it didn't seem to do anything! I also ran webpack -p for the build but it didn't seem to do anything on my 1MB test.jpg. In fact, it tried compressing svg file which actually was supposed to be embedded in my css file because I use url-loader. And moreover, it corrupted that svg!

2) How to use it along with url-loader like I can use https://github.com/thetalecrafter/img-loader

**Comment by marchaos** [comment]
It should add them to your output directory as specified in:

output: {
        path: './src/client/bin',
    ...
    },

That's a top level key in your webpack.config.js

**Comment by pavelloz** [comment]
I've been using svgo for quite some time and i agree, it sometimes produces corrupted svgs. I would suggest feeding it less agressive optimization options.

As for the second question: https://github.com/tcoopman/image-webpack-loader#usage

Basically, you can use it the same way as any other webpack loader, it will parse the query.
