### ISSUE TITLE
error with pngquant

### ISSUE THREAD

**Issue by danb-cws** [tcoopman/image-webpack-loader#42]
Hi, I am trying to deploy to Google App Engine (node). This code works fine locally and on Heroku. However on GAE, I get the following build error and the code dosnt run.
I have not been able to work out how to apply the suggested fix "make sure that libpng-dev is installed"

> pngquant-bin@3.1.1 postinstall /app/node_modules/pngquant-bin
> node lib/install.js

  ÔÜá The `/app/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ÔÜá pngquant pre-build test failed
  Ôä╣ compiling from source
  Ô£û Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by danb-cws** [comment]
Not really a resolution, but the package "img-loader" solves my problem
https://www.npmjs.com/package/img-loader
Config seems very similar.

Worth pointing out that it still throws exactly the same error on build as above, but dosnt seem to break my code

**Comment by sebastiendan** [comment]
This issue should stay open anyway, shouldn't it?

**Comment by callmecavs** [comment]
@danb-cws @sebastiendan this error has something to do with the `pngquant` quality setting, as lowering that - from `90` to `80` - fixed this issue for me.

Most likely a high quality setting leads to `pngquant` taking forever, which leads to `execa` timing out and throwing an error.

**Comment by lox** [comment]
Any idea why `execa` doesn't indicate that it's a timeout? I'm still seeing this error with lower quality settings.

**Comment by danb-cws** [comment]
Apologies for not contributing anything else to this one - for various reasons I dropped GAE in my project and went with my existing Heroku/Firebase solution.
However, I would say the error concerned compiling/building pngquant as opposed to any issues running it (eg quality settings)

**Comment by tcoopman** [comment]
If it's an error of pngquant that can't be build, can you then please
create a bug report on that project as well and link it here?

**Comment by Rolice** [comment]
I had a similar issue with CentOS 7. The binary file in the package is somehow incompatible with the Linux image (CentOS 7 latest). I have described my solution here: https://stackoverflow.com/questions/29930978/node-js-imagemin-on-centos/45567290#45567290.

**Comment by alimazrooei** [comment]
same here Please help me to solve this
