### ISSUE TITLE
[8.1.0] Compression of WebP files not working 

### ISSUE THREAD

**Issue by ghost** [tcoopman/image-webpack-loader#420]
Since I upgraded image-webpack-loader to the latest version, images in WebP format are no longer compressed.

Additional information:
- It's only version 8.1.0 that doesn't work.
- I tried using Node.js versions 12 and 15.

**Comment by agoblet** [comment]
@Luhmm1 I am facing this issue as well. Why did you close the issue? Did you solve the problem? Downgrading to 8.0 seems  like a suitable workaround for now.
