### ISSUE TITLE
ES2015 issue

### ISSUE THREAD

**Issue by caiohamamura** [tcoopman/image-webpack-loader#43]
Seems like the package ins't configured by default to be transpiled from ES2015, so when I try to use the packages, it returns errors regarding ES2015 specific syntax, shouldn't it be transpiled first?

**Comment by jsnmoon** [comment]
I'm experiencing the same problem. An example exception from a build failing to transform an enhanced object property `plugins`:
```
ERROR in ~/SomeProject/node_modules/image-webpack-loader/index.js:37
      .buffer(content, {plugins})
                               ^
Unexpected token }
```
