### ISSUE TITLE
Getting an error at jpegtran

### ISSUE THREAD

**Issue by akonyushevskiy** [tcoopman/image-webpack-loader#46]
I'm getting this error, looks like simillar to #16 : 

```
ERROR in ./src/front/components/splash/splash-mobile.jpg
Module build failed: Error: spawn /home/admin/node/greatbytrain/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./~/css-loader!./~/resolve-url-loader!./~/sass-loader!./src/front/components/splash/styles.scss 6:95-125
```
Ubuntu 12.04
node 6.7.0
npm 3.10.8

**Comment by BrainBacon** [comment]
Same here

OSX 10.11.6
node 6.7.0
npm 3.10.3

**Comment by BrainBacon** [comment]
Looks like the postinstall hook was failing to run. I went into `node_modules/jpegtran-bin` and the `vendor` folder was missing. I then ran `node lib/install.js` and that populated `vendor`.

**Comment by stevewillard** [comment]
Just ran into this too where everything works fine on my laptop:
OSX 10.12
node 6.7.0
npm 3.10.3

But then failed on my build machine, which is Ubuntu.

**Comment by akonyushevskiy** [comment]
Can't find why, but it can't build Lwip on Ubuntu and loader crashes.

**Comment by tcoopman** [comment]
@akonyushevskiy can you check the at https://github.com/EyalAr/lwip if you can find your issue there?

**Comment by akonyushevskiy** [comment]
Ok, i'm read all issues for lwip, and found solution (its seems strange, but works for me):
1) I update gcc and g++ (to 4.8.1). lwip@0.0.9 start work then, but @0.0.8 still not
2) I move loader from dev-dependencies to dependencies, and it start working. Also thats fix node-sass library. 

Thats strange. Looks like moving from dev to deps fix it on ubuntu, but on macosx system it works in both ways.

**Comment by pavelloz** [comment]
Please upgrade to 3.0.0 which uses mozjpeg -- it should serve you much better :)

**Comment by stevewillard** [comment]
I can confirm that upgrading to 3.0.0 and using mozjpeg fixed my issue. Thanks!

**Comment by pavelloz** [comment]
Glad to hear that :)

Quick survey:
Are the files smaller? Is quality better for you?

**Comment by stevewillard** [comment]
Just eyeballing the sizes, it looks about the same in both regards. It's a few kb smaller, but not much.

**Comment by pavelloz** [comment]
Thanks :)
