### ISSUE TITLE
Peer dependencies not satisified

### ISSUE THREAD

**Issue by pwang2** [tcoopman/image-webpack-loader#5]
got this error when trying to do npm install. 
As written in webpack loader guideline, 

>use a library as peerDependencies when they wrap it
>using a peerDependency allows the application developer to specify the exact version in his >package.json if he wants to. The dependency should be relative open to allow updating the library >without needing to publish a new loader version.
>
>"peerDependencies": {
 >   "library": "^1.3.5"
>}
```
npm ERR! peerinvalid The package file-loader does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer image-webpack-loader@1.3.1 wants file-loader@^0.8.1
npm ERR! peerinvalid Peer url-loader@0.5.5 wants file-loader@*
```
we should make the file-loader more open.

**Comment by tcoopman** [comment]
Hm, I don't see how this conflicts. file-loader@* should allow everything?

But I don't see the problem of letting the peerDependency more open, so I'll change the package.

**Comment by tcoopman** [comment]
Fixed in 1.4.0

**Comment by pwang2** [comment]
I am also puzzled.  If we install image-webpack-loader prior to url-loader it will be fine.   Here ^0.8.1 means file-loader should >=0.8.1 and <0.9.0.  the url-loader * actually allows file-loader version below 0.8.1, this will be treated as a mismatch. I guess.

**Comment by tcoopman** [comment]
@pwang2 I've been puzzled by peerDependencies a lot, and still don't know how to fix it properly sometimes.

Let me know if you need anything else!
