### ISSUE TITLE
Unable to load image files

### ISSUE THREAD

**Issue by EvNaverniouk** [tcoopman/image-webpack-loader#51]
After upgrading to 3.0.0, I'm getting this error:

```
 ERROR in ./static/dist/images/products/Product_Landing_Quote.jpg
[2]     Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
[2]       Referenced from: /Users/ev/Git/cumul8.com/node_modules/mozjpeg/vendor/cjpeg
[2]       Reason: image not found
[2]     
[2]         at Promise.all.then.arr (/Users/ev/Git
[2] /cumul8.com/node_modules/execa/index.js:170:11)
[2]         at process._tickCallback (internal/process/next_tick.js:103:7)
[2]      @ ./~/css-loader?module&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/stylus-loader!./src/styles/pages/Products.styl 6:2152-2225
```

This error doesn't happen on the 2.x.x version.

**Comment by mike3run** [comment]
I'm having that same issue ☹️  no idea what's going on

**Comment by mike3run** [comment]
Found the solution as random as it seems its all fixed by running `brew install libpng` wtf is going on haha

**Comment by codylindley** [comment]
Same issue, @mike3run fix, resolved it. Stinks this has to be done.

**Comment by IgorGee** [comment]
I have the same issue on Ubuntu but the solution doesn't seem to be as simple as `sudo apt install libpng` :(

**Comment by tcoopman** [comment]
This looks similar to https://github.com/imagemin/imagemin-mozjpeg/issues/23
Could you report this bug at https://github.com/imagemin/imagemin-mozjpeg?

**Comment by tcoopman** [comment]
The true reason is found here: https://github.com/imagemin/mozjpeg-bin/issues/18

**Comment by nndung179** [comment]
> Found the solution as random as it seems its all fixed by running brew install libpng wtf is going on haha

this solution worked for me. Thank @mike3run

**Comment by modernserf** [comment]
Is this "the new normal"? Will this be documented in the readme?

**Comment by tcoopman** [comment]
It would be nice if someone could document this issue in the readme and submit a PR.

**Comment by tcoopman** [comment]
I'll close this for the moment. It's not fixed but it's documented in the README (see #66). Thanks @modernserf

**Comment by Shwrndasink** [comment]
@mike3run thanks. I dunno how that brew install libpng fixed it but it did

**Comment by DavidDionise** [comment]
seriously... that's crazy. random af but THANK YOU

**Comment by jamesont** [comment]
brew install libpng did not work for me. are there other suggestions?

**Comment by mike3run** [comment]
@jamesont why don't you paste whatever the console spitted out so we can take a look.

At least the libpng thing was like that for me and several other people here, its usually right there but we don't read it the first time 😝 

We can figure this out together

**Comment by jamesont** [comment]
Thanks @mike3run ! Here is what the console is saying: 

![screen shot 2017-03-09 at 2 24 31 pm](https://cloud.githubusercontent.com/assets/14354939/23773468/30711410-04d4-11e7-9997-7f9fd2af5d6c.png)

**Comment by mike3run** [comment]
I think that error has nothing to do with this plugin it says can't resolve `../assets/big` and `../assets/small`

So maybe you did a require or import to the wrong place...

Protip its the 2 chunks of red text, you'll see more info there 😄

**Comment by jamesont** [comment]
@mike3run Thanks mike. I've tried a million things, I'm not sure where to go. This is actually from a Udemy course I've been taking online, and I've checked and re-checked the code. Can't figure out what the problem might be. I've tried messing with those file paths; nothing seems to help.

**Comment by kenguie** [comment]
@jamesont, I'm doing the same course on Webpack 2.0 ... something in webpack is broken.
run-  brew install libpng 
and it should all work after that.

**Comment by mike3run** [comment]
@kenguie just to clarify webpack has nothing to do with libpng aka this doesn't mean webpack is broken not even an issue of this loader even since this is only a thin wrapper on `imagemin` so your concerns should be directed there.

**Comment by kenguie** [comment]
Sorry, mistyped - meant to say homebrew ... I was trying to give u a note and move to the next lesson :)

**Comment by jamesont** [comment]
Thanks Ken, but I've tried brew install libpng and that had no effect. Any
other suggestions?

- Thomas

**Comment by jamesont** [comment]
Just saw this message - did you mean homebrew install libpng?

**Comment by jamesont** [comment]
Thanks Miguel,

Can you be more specific as to where to look with imagemin?

Thanks,
Thomas

**Comment by mike3run** [comment]
https://github.com/imagemin/imagemin/issues/234

**Comment by jamesont** [comment]
Awesome, I'll try that out and keep you posted. Thanks!

- Thomas

**Comment by kenguie** [comment]
I actually just typed 'brew install libpng' and after that according to my history I ran npm install so you might want to do that. But I had the same image errors because of libpng, after this it all worked out.

**Comment by forgo** [comment]
I don't have administrative privileges on the remote Red Hat build machine I am using in our environment. Why do I need to install a system-level binary to make image-webpack-loader play nicely with Node/NPM/Webpack? This should not be the case.

Has anybody looked into the long-term solution for those of us who cannot simply install libpng? Any help would be appreciated.

**Comment by mike3run** [comment]
@forgo not use this package? just go with normal file loader, this also adds an extra cpu bourden, you could process the images on your computer first and be done with it

**Comment by DWboutin** [comment]
Will it be resolved? Or the only way to get it to work is `brew install libpng` ?

**Comment by camiloei** [comment]
I solved this same issue installing 'libpng' as @kenguie said, and then installing the file-loader module:
'npm install file-loader --save-dev'.

After that I ran 'npm run build' and everything worked ok!

**Comment by jamesont** [comment]
Thank you!

**Comment by sami718** [comment]
Resolved my issue ..thanks @mike3run

**Comment by chenyiqi** [comment]
chenyiqidembp# brew install libpng
==> Downloading https://downloads.sf.net/project/libpng/libpng16/1.6.16/libpng-1.6.16.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libpng"
Download failed: https://downloads.sf.net/project/libpng/libpng16/1.6.16/libpng-1.6.16.tar.xz
chenyiqidembp#


I don`t know how to init libpng

**Comment by JoachimHarris** [comment]
Still fixing the problem one year later :dancing_men:

**Comment by bamacaerick** [comment]
I did this two things:
`brew install libpng` and then `npm install file-loader --save-dev` and everything is running fine now.

**Comment by joshhead** [comment]
In addition to `brew install libpng` I also ran `brew install automake` and `brew install nasm`. Without those, the postinstall command for the mozjpeg npm package has errors building the native mozjpeg executables on my machine.
