### ISSUE TITLE
`yarn` installation doesn't work :(

### ISSUE THREAD

**Issue by andreiconstantinescu** [tcoopman/image-webpack-loader#54]
Hello :) 

I am using this awesome loader but there seems to be a problem if installed with yarn. Out of the blue i get this error when building for production (basically if i use it)

```
ERROR in ./[...]/image.png
Module build failed: Error: spawn [...]/project-name/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

If i install the dependencies with `npm`, everything works as intended. What am I doing wrong?

Thank you!

LE: 

i'm using `webpack2` though

this happens only with `yarn 0.17`
version `0.16.1` works as intended :)

this is from the config
```
{
        test: /.*\.(gif|png|jpe?g|svg)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[path][hash].[ext]'

            }
          },
          {
            loader: 'image-webpack-loader',
            options: {
              progressive: true,
              optimizationLevel: 7,
              interlaced: false,
              pngquant: {
                quality: '65-90',
                speed: 4
              }
            }
          }
```

**Comment by luandro** [comment]
Having the same problem.

**Comment by tcoopman** [comment]
are you able to install `imagemin-pngquant` with yarn?

**Comment by adamsiwiec** [comment]
+1 Extremely annoying!

**Comment by andreiconstantinescu** [comment]
@tcoopman shouldn't it install it automatically? if it's not for `png`s, it's for `jpg`s :(

**Comment by tcoopman** [comment]
@andreiconstantinescu yeah, it should. But I have only tested with `npm` and don't have the time at the moment to check with `yarn`.

So I would love to know if it works or not if you install `imagemin-pngquant` manually. If not, it looks like it's something you should check out with `imagemin-pngquant`.

I also saw that yarn 0.18 is released, so if you can check with the latest version, that would help.

**Comment by tcoopman** [comment]
I've tested with yarn 0.18.1 and this seems to work fine.
Please reopen if you have other experiences.

**Comment by Zephir77167** [comment]
Hi,

Currently having exactly the same problem on Circle-ci (Ubuntu 64bits), with Yarn 0.24.6.

**Comment by robmccardle** [comment]
Experienced this on Debian when inside Docker. Ditching yarn and switching to npm solved it for me.
