### ISSUE TITLE
Missing ability to pass options object for gifsicle and optipng

### ISSUE THREAD

**Issue by TomDeBacker** [tcoopman/image-webpack-loader#55]
Is there a reason why you can't pass options to those two? Instead you can only supply this:

```
interlaced (for gifsicle)
optimizationLevel (for optipng)
```

**Comment by tcoopman** [comment]
Hm, probably just forgotten. Can you create a PR to fix this?

**Comment by TomDeBacker** [comment]
Sure

**Comment by tcoopman** [comment]
Fixed by your pr, thanks!
