### ISSUE TITLE
what is the difference between image-webpack-loader and img-loader?

### ISSUE THREAD

**Issue by iamstarkov** [tcoopman/image-webpack-loader#6]
these two project looks like twins. What’s the difference?
![screen shot 2015-04-14 at 17 47 07](https://cloud.githubusercontent.com/assets/559321/7140884/4ee11f5a-e2ce-11e4-8f5f-3fed34d10675.png)

**Comment by tcoopman** [comment]
No idea, didn't know about img-loader.

**Comment by tcoopman** [comment]
see discussing: https://github.com/thetalecrafter/img-loader/issues/1#issuecomment-94452920
