### ISSUE TITLE
module not found when webpack `target` is configured to `node`

### ISSUE THREAD

**Issue by mz026** [tcoopman/image-webpack-loader#7]
I was doing server-side rendering with image-loader but got `Module not found: Error: Cannot resolve module 'image'` when [`target`](http://webpack.github.io/docs/configuration.html#target) is configured to `node`.

The following is my webpack config:

```
module.exports = {
  target: 'node',
  module: {
    loaders: [
        {
            test: /\.(jpe?g|png|gif|svg)$/i,
            loaders: [
                'file?hash=sha512&digest=hex&name=[hash].[ext]',
                'image?bypassOnDebug&optimizationLevel=7&interlaced=false'
            ]
        }
    ]

  }
};
```

**Comment by tcoopman** [comment]
I just tested this with the webpack.config.js in the test directory and this works fine. Are you sure you have the image-webpack-loader installed correctly?
Does it work without `target: 'node'`?

**Comment by mz026** [comment]
It works without `target: 'node'`.
I created a repo to demonstrate the issue: https://github.com/mz026/image-loader-sample

I just found out it works with both `target`s after changing the loaders from `image?...` to `image-webpack?...`, but still don't know why it works with `image?...` + `target: 'browser'`

Thanks!

**Comment by TN1ck** [comment]
Had the same problem, changing it from `image?` to `image-webpack?` fixed it as well.

**Comment by tcoopman** [comment]
I'm going to close this, if there are still questions, please ask.
