### ISSUE TITLE
bypassOnDebug with Webpack 2

### ISSUE THREAD

**Issue by DevanB** [tcoopman/image-webpack-loader#74]
According to the docs, Webpack 2 got rid of debug mode. I'm trying to figure out if there is a new way to bypass image compression on debug now. I've tried

```
new webpack.LoaderOptionsPlugin({
       debug: true
    }),
```
as Webpack's console output suggested, but no luck.

**Comment by TomDeBacker** [comment]
#70 
This should help you out.

**Comment by DevanB** [comment]
Ahh, I had it set in each plugin, but not in the "main" area. Thanks much!

This works now:
```
query: {
  bypassOnDebug: true,
  progressive: true,
  mozjpeg: {
    quality: 65,
    bypassOnDebug: true
  },
  pngquant: {
    quality: '65-90',
    speed: 4,
    bypassOnDebug: true
  }
}
```

Along with:

```
new webpack.LoaderOptionsPlugin({
  debug: true
}),
```
