### ISSUE TITLE
How to use it for background-image?

### ISSUE THREAD

**Issue by kpgarrod** [tcoopman/image-webpack-loader#9]
Can I use this loader for `background-image url(bla)` in css? If so, how do I configure webpack/code the url?

Many thanks in advance.

**Comment by tcoopman** [comment]
What do you mean exactly? You only have url in the css file and want it minized?

If you have css-loader (https://github.com/webpack/css-loader) and image-webpack-loader configured correctly in your webpack config. The file should get minimized without any extra work. Can you check if this works?

**Comment by kpgarrod** [comment]
Yes, that's right

**Comment by tcoopman** [comment]
Could you get it working? If yes, can I close this issue?

**Comment by tcoopman** [comment]
I'm closing this issue, if you have still problems please reopen.
