### ISSUE TITLE
Error trying to load JPG images.

### ISSUE THREAD

**Issue by michaelpumo** [tcoopman/image-webpack-loader#92]
Hi,

I have been loading PNG files just fine, but today I wanted to use JPG images too. 

I get the following error:

```
ERROR in ./src/images/dimt.jpg
Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Applications/MAMP/htdocs/portfolio/node_modules/mozjpeg/vendor/cjpeg
  Reason: Incompatible library version: cjpeg requires version 36.0.0 or later, but libpng16.16.dylib provides version 27.0.0

    at Promise.all.then.arr (/Applications/MAMP/htdocs/portfolio/node_modules/execa/index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/pug/app.pug 1:5016-5045
 @ multi ./src/pug/app.pug ./src/js/app.js ./src/scss/app.scss
```

Any idea what's going on here?

Here's my webpack config for the loader section:

```
{
        test: /\.(jpe?g|png|gif)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '/images/[name].[ext]'
            }
          },
          {
            loader: 'image-webpack-loader',
            options: {
              progressive: false,
              optipng: {
                optimizationLevel: 7,
                quality: '65-70',
                speed: 4
              },
              mozjpeg: {
                quality: 90
              },
              gifsicle: {
                interlaced: false
              }
            }
          }
        ]
      }
```

Thanks

**Comment by michaelpumo** [comment]
**UPDATE**:

Referring to this issue:
https://github.com/tcoopman/image-webpack-loader/issues/51

Install brew:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Then install:
`brew install libpng`

Now it seems to work. Weird!

**Comment by forgo** [comment]
I don't have administrative privileges on the remote Red Hat build machine I am using in our environment. Why do I need to install a system-level binary to make image-webpack-loader play nicely with Node/NPM/Webpack? This should not be the case.

Has anybody looked into the long-term solution for those of us who cannot simply install libpng? Any help would be appreciated.

**Comment by tcoopman** [comment]
A long term solution is that this error is reported at the correct dependency and that they fix it.

See #51 and #93
