### ISSUE TITLE
pngquant: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by forgo** [tcoopman/image-webpack-loader#93]
```json
"image-webpack-loader": "^3.3.0"
```

I have a build process running on a remote machine via Jenkins. I am using NPM and triggering a build with the following command:

```
> npm install && npm test && NODE_ENV=production webpack --config webpack.production.config.js
```

My `webpack.production.config.js` section for image-webpack-loader looks like this:

```javascript
loader: 'image-webpack-loader',
                    options : {
                        query: {
                            mozjpeg: {
                                progressive: true
                            },
                            optipng: {
                                optimizationLevel: 7
                            },
                            gifsicle: {
                                interlaced: false
                            }
                        }
                    }
```

For every png file webpack is trying to load, I get messages that end with:

```
.../node_modules/pngquant-bin/vendor/pngquant: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```
If I manually go into this directory and execute `./pngquant`, I can indeed see that it cannot find that shared object file.

Strangely enough, on this red hat machine I am building on, this shared object is definitely available. See the output of the `locate` command below:

```bash
$ locate libpng12.so.0
/usr/lib/libpng12.so.0
/usr/lib/libpng12.so.0.50.0
```

So what's the problem here?

I have seen many references claiming that following should solve this problem:
- `npm install image-webpack pngquant` (did not work)
- `brew install libpng`
- `sudo apt-get install libpng-dev`
- ... and so on

I had the ability to run the `brew` command on my local development machine -- which I believe gave me a temporary workaround for developing.

Unfortunately, I do not have admin privileges on my build machine, and these fixes ultimately do not get to the root of the issue.

Installing a system-wide binary should not be necessary via an package dependency manager like NPM, so I'm really trying to get at the root of the issue here and wondering if anybody has an ideas.

I even tried reverting to an older image-webpack-loader version (2.0.0 from 3.3.0) because I saw someone mention that this issue did not occur for 2.x.x. Nevertheless, this did not change my outcome.

**Comment by tcoopman** [comment]
I think you already saw #51. As I said there this is an issue with a dependency of this loader, so please report it over there.

Thanks

**Comment by kopax** [comment]
Can we reopen this ? I am hitting the same issue on alpine. This seriously increase our images. I think you shouldn't use a library that ship deprecated binaries on their repo.

**Comment by tcoopman** [comment]
@kopax how do you propose this issue?

**Comment by kopax** [comment]
I would say to use to use the `libpng` available on the linux host. By default they have an up to date version or it can be installed. There is no reason to ship the lib and there are chances that it won't work on other distros.

**Comment by tcoopman** [comment]
@kopax that's something what a dependency of this loader could do. This package is not much more than a wrapper for imagemin packages. So this is not something we should solve.

**Comment by kopax** [comment]
@tcoopman is there an option that would allow the use of it on latest alpine linux ?

**Comment by tcoopman** [comment]
It should certainly be possible. But I think you are better of looking for a solution at the correct dependency repo. Maybe you can find a solution over there. If you find a solution, feel free to link it here or create a PR for the readme

**Comment by kopax** [comment]
@tcoopman do you have the repo url ? thanks!

**Comment by iamcaleberic** [comment]
`wget http://sourceforge.net/projects/libpng/files/libpng16/1.6.32/libpng-1.6.32.tar.gz/download -O libpng.tar.gz && tar -xvf libpng.tar.gz && cd libpng-1.6.32 && bash configure --prefix=/usr --disable-static &&  make install`

If you having this issue on linux this will solve it for you...if you need sudo permissions add them

**Comment by wenisy** [comment]
https://github.com/tcoopman/image-webpack-loader/issues/93#issuecomment-333367364
@iamcaleberic Thanks for your workaround, but after I tried there is still same issue with me.

I tried it on CentOS 7, I think it should be same, did I miss something?

**Comment by iamcaleberic** [comment]
@wenisy I checked and `libpng version 1.5.13-7` is available on Cent  OS packages. 
Do try
`# yum install libpng`
or
`# dnf install libpng`

Also check this thread for more on that 
`https://centos.org/forums/viewtopic.php?t=62750&p=264544`

**Comment by wenisy** [comment]
@iamcaleberic I gave you a thumb up, hope you got the notification.
Thanks again, you really solved my problem!

**Comment by hackwave** [comment]
Why not just compile this fro source instead of trusting a random binary that some random developer compiled on their random computer instead of just compiling it from source when building the JS package?

**Comment by slamorte** [comment]
None of the above fixes worked for me, but this one does:

`echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0`

**Comment by igorcaldeira** [comment]
Thanks @slamorte , helped me

**Comment by jordanmiguel** [comment]
@iamcaleberic this worked for me.
