### ISSUE TITLE
Ubuntu 17.04 libpng12.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by maraisr** [tcoopman/image-webpack-loader#95]
Given this ticket somewhat relates to #76 I decided to re-create becuase we're now at version 17.04 with still no fix?

**Error message:**

```bash
Module build failed: Error: /home/myApp/node_modules/mozjpeg/vendor/cjpeg:
error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

From [what I can see](https://askubuntu.com/a/895903/250605) I'd need to contact you guys?

----

**OS:** Ubuntu 17.04
**Version:**: mozjpeg v4.1.1

**Package**: `sudo apt-get install libpng-dev` ran with no errors:
```bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpng-dev is already the newest version (1.6.28-1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

**Comment by olalonde** [comment]
Anyone knows a work around?

**Comment by tcoopman** [comment]
As you can see, it's a problem with the dependency (mozjepg) and there is no current fix fo this. https://github.com/imagemin/mozjpeg-bin/issues/18. At mozjepg you can find a possible workaround: https://github.com/mozilla/mozjpeg/issues/255

Closing because this project can't fix this.

**Comment by olalonde** [comment]
Ah ok, using this as a workaround:

```bash
wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
  && dpkg -i /tmp/libpng12.deb \
  && rm /tmp/libpng12.deb
```

**Comment by balaindin** [comment]
Another workaround :)
```
 cd dpkg -i libpng12-0_1.2.50-2+deb8u2_amd64.deb; apt-get install -f
 sudo ln -s libpng16.so.16.28.0 libpng12.so.0
```

**Comment by Arbitr108** [comment]
what if  libpng-dev:amd64  is already installed (debian 9) and still 
"/mozjpeg/vendor/cjpeg: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory"?

**Comment by wajrou** [comment]
Same problem on Debian 9.

**Comment by majamusan** [comment]
i recommended 

```
wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
  && sudo dpkg -i /tmp/libpng12.deb \
  && rm /tmp/libpng12.deb
```

**Comment by VladimirVaivada** [comment]
Sorry my English... I just installed mozjpeg@5.0.0 package and delete old mozjpeg@4.1.1 from image-webpack-loader node_modules. And it works! I had same error message:

**Comment by Nexxado** [comment]
Downgrading `image-webpack-loader` to `v3.6.0` solved it for me:
`yarn add image-webpack-loader@^3.6.0`

**Comment by mikeherrera** [comment]
I got passed this on CentOS 7 through a combination of a lot of cursing and `yum install libpng12.x86_64 libpng12-devel.x86_64`

**Comment by slamorte** [comment]
None of the above fixed worked for me. 

This one-liner solved it:

`echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0`

This installed libpng12 and doesn't require uninstalling libpng-dev (16.34 as of this comment). The issue appears to reside in a node package or webpack configuration and I wish it could be resolved there. In the meantime loading an old, outdated, buggy revision of libpng allows the build to proceed.

**Comment by bpauldun** [comment]
@slamorte Nice one. This fix works great. Thank you

**Comment by satishsamalanz** [comment]
Thanks @slamorte. Your fix worked for me. Cheers !!

**Comment by joscha** [comment]
> echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0

Does this solution work for anyone in `sid`? I can't seem to get it installed due to
```
Preparing to unpack .../libpng12-0_1.2.54-1ubuntu1_amd64.deb ...
Unpacking libpng12-0:amd64 (1.2.54-1ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/libpng12-0_1.2.54-1ubuntu1_amd64.deb (--install):
 unable to install new version of '/lib/x86_64-linux-gnu/libpng12.so.0': No such file or directory
Processing triggers for libc-bin (2.27-6) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libpng12-0_1.2.54-1ubuntu1_amd64.deb
```

**Comment by robotshateme** [comment]
"echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0"
Worked for me.

**Comment by matheusfrancisco** [comment]
> Ah ok, using this as a workaround:
> 
> ```shell
> wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
>   && dpkg -i /tmp/libpng12.deb \
>   && rm /tmp/libpng12.deb
> ```

work to me on debian 9.4

**Comment by ErwinCraps** [comment]
> None of the above fixes worked for me.
> 
> This one-liner solved it:
> 
> `echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0`
> 
> This installed libpng12 and doesn't require uninstalling libpng-dev (16.34 as of this comment). The issue appears to reside in a node package or webpack configuration and I wish it could be resolved there. In the meantime loading an old, outdated, buggy revision of libpng allows the build to proceed.

Worked for me on Ubuntu 18.04.1 LTS which is Hyper-V Win 10 Quick create one.
I needed this because ODOO has issues generating mail/pdf's at least in the sales module.
Thank you.

**Comment by tomwj** [comment]
Ended up here from Arch ( Manjaro ). This fixed it.
```sudo pacman -S libpng12```

**Comment by Deen598** [comment]
> > None of the above fixes worked for me.
> > This one-liner solved it:
> > `echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0`
> > This installed libpng12 and doesn't require uninstalling libpng-dev (16.34 as of this comment). The issue appears to reside in a node package or webpack configuration and I wish it could be resolved there. In the meantime loading an old, outdated, buggy revision of libpng allows the build to proceed.
> 
> Worked for me on Ubuntu 18.04.1 LTS which is Hyper-V Win 10 Quick create one.
> I needed this because ODOO has issues generating mail/pdf's at least in the sales module.
> Thank you.

Thank you Erwin, it solved mine

**Comment by kupoback** [comment]
> > > None of the above fixes worked for me.
> > > This one-liner solved it:
> > > `echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0`
> > > This installed libpng12 and doesn't require uninstalling libpng-dev (16.34 as of this comment). The issue appears to reside in a node package or webpack configuration and I wish it could be resolved there. In the meantime loading an old, outdated, buggy revision of libpng allows the build to proceed.
> > 
> > 
> > Worked for me on Ubuntu 18.04.1 LTS which is Hyper-V Win 10 Quick create one.
> > I needed this because ODOO has issues generating mail/pdf's at least in the sales module.
> > Thank you.
> 
> Thank you Erwin, it solved mine

Thank you as well. Worked for me on Ubuntu 18.04

**Comment by campaignupgrade** [comment]
Recently my deploy process starting throwing errors regarding keys. 

This new three-line bash fixes that issue:

```bash
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
            echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0
```

**Comment by campaignupgrade** [comment]
If anyone has a better fix, perhaps using a new version of mozjepg, I'd be happier to replace this hacky fix.

**Comment by shaohuaXu** [comment]
> None of the above fixes worked for me.
> 
> This one-liner solved it:
> 
> `echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0`
> 
> This installed libpng12 and doesn't require uninstalling libpng-dev (16.34 as of this comment). The issue appears to reside in a node package or webpack configuration and I wish it could be resolved there. In the meantime loading an old, outdated, buggy revision of libpng allows the build to proceed.

> This installed libpng12 and doesn't require uninstalling libpng-dev (16.34 as of this comment). The issue appears to reside in a node package or webpack configuration and I wish it could be resolved there. In the meantime loading an old, outdated, buggy revision of libpng allows the build to proceed.

I tried this one and it worked .  Thanks~~~

**Comment by amayer-glei** [comment]
Getting this error now with node:8 Docker image in a multistage build...

**Comment by trickdgrit** [comment]
> i recommended
> 
> ```
> wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
>   && sudo dpkg -i /tmp/libpng12.deb \
>   && rm /tmp/libpng12.deb
> ```

i try this one and it's working for me in my ubuntu 18.04, thank you.

**Comment by bini414** [comment]
finally  this help me in kali linux 2020

This new three-line bash fixes that issue:

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0
sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0

**Comment by brilliant-smart** [comment]
> None of the above fixes worked for me.
> 
> This one-liner solved it:
> 
> `echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0`
> 
> This installed libpng12 and doesn't require uninstalling libpng-dev (16.34 as of this comment). The issue appears to reside in a node package or webpack configuration and I wish it could be resolved there. In the meantime loading an old, outdated, buggy revision of libpng allows the build to proceed.

I got this error:
 unable to install new version of '/lib/x86_64-linux-gnu/libpng12.so.0': No such
 file or directory
Errors were encountered while processing:
 /var/cache/apt/archives/libpng12-0_1.2.54-1ubuntu1_amd64.deb
Scanning application launchers
Updating active launchers
Done
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by brilliant-smart** [comment]
None of the above fix worked for me, I am using parrot 5.4

**Comment by shrutikabongarde** [comment]
> None of the above fixes worked for me.
> 
> This one-liner solved it:
> 
> `echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0`
> 
> This installed libpng12 and doesn't require uninstalling libpng-dev (16.34 as of this comment). The issue appears to reside in a node package or webpack configuration and I wish it could be resolved there. In the meantime loading an old, outdated, buggy revision of libpng allows the build to proceed.

its really awesome>>> Worked for me

**Comment by delmicio** [comment]
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0
sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0

unfortunately it fails on ARM (M1)
